# Generated by Django 5.2.16 on 2026-07-19 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, help_text='Estimated course duration in minutes.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
